package jsd.project.tank90.entities;

public enum BulletType {
    STANDARD, STANDARD_TIER_2, STANDARD_TIER_3, STANDARD_TIER_4,
    EXPLOSIVE, EXPLOSIVE_TIER_2, EXPLOSIVE_TIER_3, EXPLOSIVE_TIER_4,
    RAPID, RAPID_TIER_2, RAPID_TIER_3, RAPID_TIER_4
}
